<a href="https://colab.research.google.com/github/syntaxking-7/FAP_assignment1/blob/main/FAP_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Part 1: Data Exploration with Pandas

import pandas as pd
import numpy as np

# loading the dataset
df = pd.read_csv("/content/sample_data/california_housing_train.csv") # importing the csv file into pyhton notebook
print("The first 5 rows : ")
print(df.head(5)) # displays first 5 rows
print()
print("The last 10 rows : ")
print(df.tail(10)) # displays last 10 rows
print()

# data summary
print(df.describe()) # fucntion used for statistical analysis
unique = df['total_bedrooms'].nunique() # used to count number of unique elements
print("The number of unique elements are : ",unique)
print()

# data transformation
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms']/df['total_rooms'] # addition of new columns as specified
mean = df['total_bedrooms_per_total_rooms'].mean() # using mean and std functions to calculate mean and standard deviation resp
standard_deviation = df['total_bedrooms_per_total_rooms'].std()
print("The mean for the column total_bedrooms_per_total_rooms is ",mean," and standard deviation is ",standard_deviation)
print()

# data filtering
df_filtered_1 = df[df['median_income']>5] #Filtering the dataset to find rows where the median_income is greater than 5
df_filtered_2 = df[(df['total_rooms']>10000) & (df['median_house_value']<150000)] # filtering as per second condition and printing it
print("The subset formed which satisfies the given conditions : ")
print(df_filtered_2)
print()

# exporting modified data
df.to_csv('modified_data.csv')

The first 5 rows : 
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  

The last 10 rows : 
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0     

In [ ]:
# Part 2 : Numerical Analysis with NumPy

import pandas as pd
import numpy as np

# Array creation and indexing
array1D = np.arange(1,21) # creating a 1-D array from 1 to 20
array1D_even = array1D[1:21:2] # slicing with start index as 1 and step size as 2
array2D = np.random.randint(10,101,size = (5,4)) # creating 5 * 4 matrix using random function
array2D_extracted = array2D[0:3,0:2] # creating the sub-matrix
print("The creates 2D array of 5*4 order with integers from o to 100 : ")
print(array2D)
print("The extracted 3 * 2 subarray from the above 2D array : ")
print(array2D_extracted)
print()

# Array Manipulation
reshape_1D_into_2D = np.reshape(array1D, (4,5)) #creating a 2-D matrix of 4*5
reshape_2D_into_1D = np.reshape(reshape_1D_into_2D,(1,20)) # falttening the 2D matrix into an array and printing it
print("The flattened 1D array created from the 2D array : ")
print(reshape_2D_into_1D)

array2D_generated = np.random.randint(10,101,size = (5,4)) # randomly generating a 2-D matrix of order 5 * 4 and multiplying it with 2-D matrix of 1-20.
multiplied_matrix = np.matmul(reshape_1D_into_2D,array2D_generated)
print("The matrix formed from the result of multiplication : ")
print(multiplied_matrix)
print()

# Boolean And Fancy Indexing
array_new = np.random.randint(0,101,50)

array_new_extracted_boolean = array_new[array_new>50] # generates an array of all elements greater than 50
print("The extracted array using boolean values : ")
print(array_new_extracted_boolean)

indices = [12,32,18,41] # take random indexes whose values we need to access
array_new_extracted_fancy = array_new[indices]
print("The extracted array using specified indices : ")
print(array_new_extracted_fancy)
print()

# Statistical Operations (The 2-D array which i have used is the randomly generated one)
# I have also printed the array on which i have done the operations on

print(" I have used the follwing array for this part: ")
print(array2D)

# specifying axis = 0 to operate on columns only
print("Mean along columns : ",np.mean(array2D,axis = 0))
print("Max along columns : ",np.max(array2D,axis = 0))
print("Sum along columns : ",np.sum(array2D,axis = 0))

# Creating the mask and using it to filter the matrix
mask = (array2D> np.mean(array2D,axis = 0))
array2D_masked = array2D[mask]
print("The subarray satisfying the condition (created using mask) : ")
print(array2D_masked)

The creates 2D array of 5*4 order with integers from o to 100 : 
[[100  87  62  20]
 [ 79  71  57  70]
 [ 85  49  16  42]
 [ 94  72  95  14]
 [ 27  93  96  65]]
The extracted 3 * 2 subarray from the above 2D array : 
[[100  87]
 [ 79  71]
 [ 85  49]]

The flattened 1D array created from the 2D array : 
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
The matrix formed from the result of multiplication : 
[[ 744  782  843  843]
 [1994 2312 2298 2348]
 [3244 3842 3753 3853]
 [4494 5372 5208 5358]]

The extracted array using boolean values : 
[63 92 99 58 68 83 64 94 58 64 70 88 87 97 66 59 79 88 56 96 83 53 53 52
 91 90 70 54 78 54 60 67 86 94]
The extracted array using specified indices : 
[11 83 97 78]

 I have used the follwing array for this part: 
[[100  87  62  20]
 [ 79  71  57  70]
 [ 85  49  16  42]
 [ 94  72  95  14]
 [ 27  93  96  65]]
Mean along columns :  [77.  74.4 65.2 42.2]
Max along columns :  [100  93  96  70]
Sum along columns :  [385 372 326 211]
The su

In [ ]:
# Part 3 : Problem Solving with Python Basics

# loops and conditional statements
# 1) Printing Fibonacci

a,b = 0,1
while a<=100:
  print(a,end = " ")
  temp = a+b
  a = b
  b = temp
print()

0 1 1 2 3 5 8 13 21 34 55 89 


In [ ]:
# loops and conditional statements
# 2) Loop through numbers

i = 1
while i<=50:
  if(i%3 == 0 and i%5 == 0) : print(i," FizzBuzz")
  elif (i%3 == 0) : print(i," Fizz")
  elif (i%5 == 0) : print(i," Buzz")
  i = i+1

3  Fizz
5  Buzz
6  Fizz
9  Fizz
10  Buzz
12  Fizz
15  FizzBuzz
18  Fizz
20  Buzz
21  Fizz
24  Fizz
25  Buzz
27  Fizz
30  FizzBuzz
33  Fizz
35  Buzz
36  Fizz
39  Fizz
40  Buzz
42  Fizz
45  FizzBuzz
48  Fizz
50  Buzz


In [ ]:
# Variable-length arguments
#1) Median
list_num = []
print("Enter numbers whose median has to be calculated(when completed type finish)")
while True :
  a = input()
  if a=="finish" :
    break
  else :
    num = int(a)
    list_num.append(num)
list_len = len(list_num)
list_num.sort()

if list_len % 2 == 0:
  median = (list_num[list_len//2] + list_num[list_len//2 - 1])/2
  print(median)
else :
  median = list_num[list_len//2]
  print(median)

Enter numbers whose median has to be calculated(when completed type finish)
12
423
22
12
233
12
finish
17.0


In [ ]:
# Variable-length arguments
#2) Mean
list_num = []
print("Enter numbers whose median has to be calculated(when completed type finish)")
while True :
  a = input()
  if a=="finish" :
    break
  else :
    num = int(a)
    list_num.append(num)
list_len = len(list_num)
list_sum = sum(list_num)
mean = list_sum/list_len
print(mean)

Enter numbers whose median has to be calculated(when completed type finish)
1
2
3
12
finish
4.5


In [ ]:
# Error Handling
a = input("Enter num1 : ")
b = input("Enter num2 : ")
if b == 0:
  print("Division by 0 not allowed!")
else :
  print("result of num1/num2 : ",int(a)/int(b))


Enter num1 : 12
Enter num2 : 12
result of num1/num2 :  1.0


In [ ]:
# Advanced NumPy Manipulation

import numpy as np
import pandas as pd

a = int(input("Enter 1st dimension : "))
b = int(input("Enter 2nd dimension : "))
c = int(input("Enter 3rd dimension : "))

array_3D = np.random.randint(0,101,size = (a,b,c)) # creates a 3D array with random integers from 0 to 100
print(array_3D)
print()

swapped_array_3D = np.swapaxes(array_3D,0,1) # we swap 1st and 2nd dimension so the swapped_array is a 3-D array with dimensions 3*2*4
print(swapped_array_3D)
print()

sum_along_axes = np.sum(array_3D,axis = 0)
print(sum_along_axes)

Enter 1st dimension : 2
Enter 2nd dimension : 3
Enter 3rd dimension : 4
[[[58 19 15 19]
  [75 68 24 21]
  [13 30 54 52]]

 [[12 54 73 65]
  [63 62  0 50]
  [57 84 29 23]]]

[[[58 19 15 19]
  [12 54 73 65]]

 [[75 68 24 21]
  [63 62  0 50]]

 [[13 30 54 52]
  [57 84 29 23]]]

[[ 70  73  88  84]
 [138 130  24  71]
 [ 70 114  83  75]]


In [ ]:
import numpy as np
import pandas as pd

array2D = np.random.randint(0,101,(3,4)) # creating a random 2D array with elements from o to 100 of order 3*4
vector = np.array([1,2,3,4])

new_2D_array = array2D + vector
print("Original Matrix : ")
print(array2D)
print("New Matrix : ")
print(new_2D_array)



Original Matrix : 
[[39  6 30 38]
 [65 18 46  9]
 [13 23  8 65]]
New Matrix : 
[[40  8 33 42]
 [66 20 49 13]
 [14 25 11 69]]
